kind: Secret
apiVersion: v1
metadata:
  name: fast-webapp
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    app: webapp
data:
  django-secret-key: ''
  postgres-db-user: ''
  postgres-db-password: ''
  dark-sky-api-key: ''
  mapquest-api-key: ''
  fast-webapp-default-django-password: ''
