apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: kafka
  labels:
    app: zookeeper
    release: fast-platform-v0.1
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zookeeper
    release: fast-platform-v0.1

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: kafka
  labels:
    app: zookeeper
    release: fast-platform-v0.1
spec:
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
  clusterIP: None
  selector:
    app: zookeeper
    release: fast-platform-v0.1

