apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fast-webapp-postgres
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    app: webapp-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: cinder