kind: Secret
apiVersion: v1
metadata:
  name: fast-webapp-postgres
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    app: webapp-postgres
data:
  postgres-user: ''
  postgres-password: ''
