apiVersion: v1
kind: Service
metadata:
  name: fast-webapp-postgres
  namespace: fast-platform
  labels:
    platform: fast
    module: core
    app: webapp-postgres
spec:
  type: ClusterIP 
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    platform: fast
    module: core
    app: webapp-postgres
