apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: kafka
  labels:
    app: kafka
    release: fast-platform-v0.1
spec:
  ports:
  - name: broker
    port: 9092
  - name: jmx-exporter
    protocol: TCP
    port: 5555
    targetPort: 5556
  selector:
    app: kafka
    release: fast-platform-v0.1

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: kafka
  labels:
    app: kafka
    release: fast-platform-v0.1
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: broker
    port: 9092
  clusterIP: None
  selector:
    app: kafka
    release: fast-platform-v0.1

---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
    release: fast-platform-v0.1
spec:
  ports:
  - name: kafka-exporter
    protocol: TCP
    port: 9308
    targetPort: 9308
  selector:
    app: kafka-exporter
    release: fast-platform-v0.1

